各ページ内リンクの遷移をGatsby Linkを使用する
aws-amplify-jp/aws-amplify-jp.github.io pull request #30
Opened 2021-07-14 04:28 UTC by itomise

ページ内リンクの遷移が非同期ではなく同期になっていたので、GatsbyのLinkコンポーネントをWrapしたコンポーネントを作成して書き換えた。

2021-07-14 04:40 UTC, watilde commented on src/components/common/Link.js
> +export default function Link({ children, ...all }) {
こちら共通部品としてかなり使い回す気がするので、もしよければcomponents以下に移動お願いできますでしょうか :)

2021-07-14 04:41 UTC, watilde commented on src/components/Footer.js
> +    color: Theme.palette.primary.main
カラーもcomponent側で実装できると幸いです！

2021-07-14 04:42 UTC, watilde commented on src/components/Footer.js
> +                <Link to="/" className={classes.link}>
こちらのリンク先は、本リポジトリのままでお願いできると幸いです 🙏

2021-07-14 04:42 UTC, watilde requested changes
GatsbyのLink知らなかったので、とても参考になります！ありがとうございます :)
細かいところですが、いくつかコメントさせていただきました。

2021-07-14 10:00 UTC, itomise commented on src/components/common/Link.js
> +export default function Link({ children, ...all }) {
こちら、サイト全体のレイアウトにかかわるコンポーネントと単純なコンポーネントを分ける目的だったのですがいかがでしょうか？？（ほかのコンポーネントはすべてサイト全体のレイアウトにかかわるコンポーネントだったため）

2021-07-14 10:43 UTC, watilde commented on src/components/common/Link.js
> +export default function Link({ children, ...all }) {
返信ありがとうございます！おっしゃるとおりで、現状のcomponentsは全体で使われるものばかりですね。思想としては、Atomic designを参考に、パーツは`components`でページは`container`に入れる思想でやってみているところです。このへんドキュメント書けていなかったので、どこかで書いてみますね :)
Refs: https://blog.usejournal.com/thinking-about-react-atomically-608c865d2262

ちなみになんですが、ロジックがあまりないので`Presentational and Container Components `的なデザインパターンはまだ不要かなと思っているところです。

2021-07-14 11:06 UTC, itomise commented
@watilde 
諸々反映させていただきました！
クラス名のマージ用に classnames のパッケージ追加させていただいたのですが、それも問題ないかご確認お願いします！

2021-07-14 14:30 UTC, watilde approved these changes
ありがとうございます！

2021-07-16 10:12 UTC, itomise commented
@watilde コンフリクト解消いたしました！

2021-07-18 07:21 UTC, watilde approved these changes

2021-07-18 07:21 UTC, merged

2021-07-18 07:23 UTC, watilde commented
Niceです！コンフリクトの解決いい感じにできていました。
Rebaseするとコミットログをシンプルにできるので、次回一緒にやらせてください :)